version: '3.8'

services:
  eventstore:
    image: eventstore/eventstore:5.0.2-buster
    container_name: eventstore
    ports:
      - "2113:2113"  # HTTP API
      - "1113:1113"  # TCP
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INT_TCP_PORT=1113
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2113
      - EVENTSTORE_EXT_HTTP_PORT=2113
    volumes:
      - eventstore_data:/var/lib/eventstore
      - eventstore_logs:/var/log/eventstore
    restart: unless-stopped

volumes:
  eventstore_data:
  eventstore_logs: