// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEducacao.Gestao.Data;

#nullable disable

namespace PlataformaEducacao.Gestao.Data.Migrations
{
    [DbContext(typeof(GestaoContext))]
    partial class GestaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("PlataformaEducacao.Gestao.Domain.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacao.Gestao.Domain.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacao.Gestao.Domain.Matricula", b =>
                {
                    b.HasOne("PlataformaEducacao.Gestao.Domain.Aluno", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PlataformaEducacao.Gestao.Domain.CursoMatriculado", "Curso", b1 =>
                        {
                            b1.Property<Guid>("MatriculaId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("CursoId")
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("CursoNome")
                                .IsRequired()
                                .HasColumnType("varchar(150)");

                            b1.Property<int>("CursoTotalAulas")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("CursoValor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("MatriculaId");

                            b1.ToTable("Matriculas");

                            b1.WithOwner()
                                .HasForeignKey("MatriculaId");
                        });

                    b.Navigation("Aluno");

                    b.Navigation("Curso")
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEducacao.Gestao.Domain.Aluno", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
