// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEducacao.GestaoCursos.Data;

#nullable disable

namespace PlataformaEducacao.GestaoCursos.Data.Migrations
{
    [DbContext(typeof(GestaoCursosContext))]
    [Migration("20250601132417_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("PlataformaEducacao.GestaoCursos.Domain.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacao.GestaoCursos.Domain.Curso", b =>
                {
                    b.OwnsOne("PlataformaEducacao.GestaoCursos.Domain.ConteudoProgramatico", "ConteudoProgramatico", b1 =>
                        {
                            b1.Property<Guid>("CursoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Conteudo")
                                .IsRequired()
                                .HasColumnType("varchar(500)")
                                .HasColumnName("Conteudo");

                            b1.Property<string>("Objetivo")
                                .IsRequired()
                                .HasColumnType("varchar(500)")
                                .HasColumnName("Objetivo");

                            b1.HasKey("CursoId");

                            b1.ToTable("Cursos");

                            b1.WithOwner()
                                .HasForeignKey("CursoId");
                        });

                    b.Navigation("ConteudoProgramatico")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
